import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vogz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="firstPart">
        <img src={'/selfiePhone.png'} alt="" className='none'/>
        <img src={'/firstColumn.png'} alt="" className='firstImage'/>
        <img src={'/secondColumn.png'} alt="" className='secondImage'/>
        <img src={'/thirdColumn.png'} alt="" className='firstImage'/>
        <img src={'/fourColumn.png'} alt="" className='firstImage'/>
        <img src={'/phone3.png'} alt="" className='phoneImage'/>
        <img src={'/arrowBottom.png'} alt="" className='arrowBottomImage'/>
      </div>


      <div className="secondPart">
        <div className="text">
          <h3>Tu es créateur de contenu et tu sais le rendre <span>captivant</span> et <span>original ?</span></h3>
          <h5>Devient <span>Yogzter</span> et fais partie de nos <span>30 BETA TESTEUR, </span><span className="highlight">l'objectif :</span> créer les <span>VOGZ</span> les plus <span className='highlight'>engageantes</span> pour toutes les marques de notre <span className='highlight'>communauté !</span></h5>
        </div>

        <div className="imgSelfie">
          <img src={'/manSelfie.png'} alt=""/>
        </div>

        <img src={'/fuseeRouge.png'} alt="" className="fuseeRouge"/>
      </div>

      <div className="thirdPart flex-around">
          <img src={'/selfieMom.png'} alt="" className="selfieMom"/>
        <div className="text">
          <h3>*Une <span>VOGZ</span> ?</h3>
          <h5>Une <span>VOGZ</span> est <span className="highlight">une vidéo</span> réalisée par un <span>Vogzter</span>. Elle répond au <span className="highlight">brief d'un client</span>, et se veut créative, authentique, mais surtout, elle doit être à <span className="highlight">l'image de son créateur :</span> <br/><span className="bigText">GRANDIOSE</span></h5>

          <div className="buttonContainer">

            <img src={'/inscription3.png'} alt="" className="imgInscription"/>
            {/* <div className="inscriptionButton">
              <h5 className='inscriptionText'>S'INSCRIRE</h5>
            </div>

            <div className="arrowRed">
              <img src={'/redArrow.png'} alt=""/>
              <p>Original</p>
            </div>
            */}
          </div>
        </div>
      </div>

      <div className="fourPart">
        <div className="crown">
          <img src={'/crown.png'} alt="" className='crownImg'/>
        </div>
        <h3>AU ROYAUME DU <br/>CONTENU, LES VOGZTERS <br/>SONT <span>ROIS</span></h3>

        <div className="descriptionContainer">
          <h5><span className="fatText">VOGZ</span> est une nouvelle plateforme innovante pensée pour les <span className='pinkHighlight'>créateurs de contenus</span> et à destination des <span className='pinkHighlight'>marques</span> voulant communiquer de la façon la plus authentique possible auprès de leur <span className='pinkHighlight'>communauté</span> </h5>
        </div>

        <h2>Répondez à vos premiers briefs...</h2>

        <img src={'/phoneImg.png'} alt="" className='none'/>
        <div className="premiers">
          <img src={'/premiers.png'} alt="" className="premiersImg"/>
        </div>

        <h2 className='revenuesText'>Et générez vos premiers revenus
          grâce à vos productions ! </h2>


        <div className="inscriptionButton">
          <h5 className='inscriptionText'>S'INSCRIRE</h5>
        </div>

      </div>

      <div className="fivePart">
        {/*
        <div className="photoMontage">
          <img src={'/photoMontage.png'} alt="" className='photoMontageImg'/>
        </div>
        <img src={'/arrowYellow.png'} alt="" className='firstArrow'/>
        <img src={'/VerteFusee.png'} alt="" className='secondArrow'/>
        */}
        <img src={'/photomontage2.png'} alt="" className="photomontage2"/>

        <img src={'/photoMontage.png'} alt="" className='noneImg'/>
        <div className="textPhotoMontage">
          <h3>Devenir <span>Yogzter</span>...</h3>
          <h5>C’est entrer dans une <span>communauté créative</span> aux contenus <span>rigoureux</span> et <span>efficaces.</span></h5>
        </div>
        </div>


      <footer className='flex-between'>
            <div className="bientot">
              <img src={'/play.png'} alt="" className="play"/>
              <h2>Bientôt disponible sur</h2>
              <div className="flex googleContainer">
                <img src={'/googlePlay.png'} alt="" className="googlePlay"/>
                <h5 className="esper">&</h5>
                <img src={'/appStore.png'} alt="" className="applePay"/>
              </div>
            </div>
            <div className="avis">
              <img src={'/hat.png'} alt="" className='hat'/>
              <h3>Avis aux <span>pionniers</span> !</h3>
              <h5>Nous sommes à la recherche de nos <span>30 premiers vogzters.</span> C'est le moment pour toi de te lancer, rejoins dès <span>maintenant</span> l'aventure <span className="fatText">Vogz</span> !</h5>
              <form action="">
                <div className="inputContainer">
                <input type="text" placeholder='Nom'/>
                <input type="text" placeholder="Prénom"/>
                <input type="text" placeholder="Adresse Mail"/>
                <input type="text" placeholder="Téléphone"/>
                </div>
                <div className="contactButton">
                  <h5 className='inscriptionText'>ENVOYER</h5>
                </div>
              </form>

            </div>
      </footer>
    </div>
  )
}
