import React, {useState, useRef} from 'react';
import Head from 'next/head'
import ReactPlayer from 'react-player'
import {Formik} from 'formik';
import Footer from "../components/Footer";
import {Link} from 'react-scroll';
import ReCAPTCHA from 'react-google-recaptcha';
import axios from 'axios';

import * as Yup from 'yup';

export default function Home() {

  const initialValues = {
    nom: '',
    prenom: '',
    email: '',
    phone: ''
  }

  const SignupSchema = Yup.object().shape({
    email: Yup.string().email('Veuillez rentrer une adresse mail valide').required('Veuillez rentrer une adresse mail'),
    phone: Yup.string().matches(/^0[1-7]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})|((-[0-9]{2}){4})$/, "Entrez un numéro valide")
  });


  const reRef = useRef();

  return (
    <div>
      <Head>
        <title>Vogz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="../dist/devices.css"/>
      </Head>

      <div className="firstPart">
        <video src={'/video.mp4'} className="video-presentation none" autoPlay muted/>

        <img src={'/firstColumn.png'} alt="" className='firstImage'/>
        <img src={'/secondColumn.png'} alt="" className='secondImage'/>
        <img src={'/thirdColumn.png'} alt="" className='firstImage'/>
        <img src={'/fourColumn.png'} alt="" className='firstImage'/>

        <div className="device device-iphone-x" id="picture">
          <div className="device-frame">
            <video src={'/video.mp4'} className="device-content" autoPlay muted/>
          </div>
        </div>

        <Link activeClass="active" to="secondPart" spy={true} smooth={true}><img src={'/arrowBottom.png'} alt="" className='arrowBottomImage'/></Link>
      </div>

      <div className="secondPart" id="secondPart">
        <div className="text">
          <h3>Tu es créateur de contenu et tu sais le rendre <span>captivant</span> et <span>original ?</span></h3>
          <h5>Devient <span className="grasBlue">Vogzter</span> et fais partie de nos <span className="grasBlue">30 BETA TESTEUR, </span><span className="highlight">l'objectif :</span> créer les <span className="grasBlue">VOGZ</span> les plus <span className='highlight'>engageantes</span> pour toutes les marques de notre <span className='highlight'>communauté !</span></h5>
        </div>

        <img src={'/filConducteur.png'} alt="" className='filConducteur none'/>

        <div className="imgSelfie">
          <img src={'/manSelfie.png'} alt=""/>
        </div>
        <img src={'/fuseeRouge.png'} alt="" className="fuseeRouge"/>
      </div>

      <div className="thirdPart flex-around">
          <img src={'/selfieMom.png'} alt="" className="selfieMom"/>
        <div className="text">
          <h3>*Une <span>VOGZ</span> ?</h3>
          <h5>Une <span className="grasBlue">VOGZ</span> est <span className="highlight">une vidéo</span> réalisée par un <span className="grasBlue">Vogzter</span>. Elle répond au <span className="highlight">brief d'un client</span>, et se veut créative, authentique, mais surtout, elle doit être à <span className="highlight">l'image de son créateur :</span> <br/><span className="bigText grasBlue">GRANDIOSE</span></h5>

          <div className="buttonContainer">

           <Link activeClass="active" to="inscription" spy={true} smooth={true}> <img src={'/inscription3.png'} alt="" className="imgInscription"/></Link>
            {/* <div className="inscriptionButton">
              <h5 className='inscriptionText'>S'INSCRIRE</h5>
            </div>

            <div className="arrowRed">
              <img src={'/redArrow.png'} alt=""/>
              <p>Original</p>
            </div>
            */}
          </div>
        </div>
      </div>

      <div className="fourPart">
        <div className="crown">
          <img src={'/crown.png'} alt="" className='crownImg'/>
        </div>
        <img src={'/yellowFusee.png'} alt="" className="yellowFusee"/>
        <h3>AU ROYAUME DU <br/>CONTENU, LES VOGZTERS <br/>SONT <span className="rois">ROIS</span> !</h3>

        <div className="descriptionContainer">
          <h5><span className="fatText">VOGZ</span> est une nouvelle plateforme innovante pensée pour les <span className='pinkHighlight'>créateurs de contenus</span> et à destination des <span className='pinkHighlight'>marques</span> voulant communiquer de la façon la plus authentique possible auprès de leur <span className='pinkHighlight'>communauté</span> </h5>
        </div>

        <h2>R<span>épondez à vos premiers briefs...</span></h2>

        <img src={'/phoneImg.png'} alt="" className='none'/>
        <div className="premiers">
          <img src={'/premiers.png'} alt="" className="premiersImg"/>
        </div>

        <h2 className='revenuesText'>E<span>t générez vos premiers revenus
          grâce à vos productions ! </span></h2>


        <Link activeClass="active" to="inscription" spy={true} smooth={true}>
          <div className="inscriptionButton">
            <h5 className='inscriptionText'>S'INSCRIRE</h5>
          </div>
        </Link>


      </div>

      <div className="fivePart">
        {/*
        <div className="photoMontage">
          <img src={'/photoMontage.png'} alt="" className='photoMontageImg'/>
        </div>
        <img src={'/arrowYellow.png'} alt="" className='firstArrow'/>
        <img src={'/VerteFusee.png'} alt="" className='secondArrow'/>
        */}
        <img src={'/photomontage2.png'} alt="" className="photomontage2"/>

        <img src={'/filConducteur2.png'} alt="" className="filConducteur2 none" />
        <img src={'/filConducteur2.png'} alt="" className="filConducteur3 none" />

        <img src={'/photoMontage.png'} alt="" className='noneImg'/>
        <div className="textPhotoMontage">
          <h3>Devenir <span>VOGZTER</span>...</h3>
          <h5>C’est entrer dans une <span>communauté créative</span> aux contenus <span>rigoureux</span> et <span>efficaces.</span></h5>
        </div>
        </div>


      <div className='flex-between footer' id='inscription'>
            <div className="bientot">
              <img src={'/play.png'} alt="" className="play"/>
              <h2>Disponible sur</h2>
              <div className="flex googleContainer">
                <img src={'/googlePlay.png'} alt="" className="googlePlay"/>
                <h5 className="esper">&</h5>
                <img src={'/appStore.png'} alt="" className="applePay"/>
              </div>
            </div>
            <div className="avis">
              <img src={'/hat.png'} alt="" className='hat'/>
              <h3>Avis aux <span>pionniers</span> !</h3>
              <h5>Nous sommes à la recherche de nos <span className='highlight-light-blue'>30 premiers vogzters.</span> C'est le moment pour toi de te lancer, rejoins dès <span className='highlight-light-blue'>maintenant</span> l'aventure <span className="fatText">VOGZ</span> !</h5>
              <Formik
                initialValues={initialValues}
                validationSchema={SignupSchema}
                onSubmit={async (values) => {
                  const token = await reRef.current.executeAsync();
                  reRef.current.reset();

                  try {
                    await axios.post('/api/send-email', {
                      values,
                      token
                    })
                  } catch(err) {
                    console.log(err)
                  }
                  console.log(values)
                }}
              >
                {props => (
                  <form action="">
                    <div className="inputContainer">
                      <input
                        type="text"
                        placeholder='Prénom'
                        value={props.values.prenom}
                        onChange={props.handleChange('prenom')}
                      />
                      <input
                        type="text"
                        placeholder="Nom"
                        value={props.values.nom}
                        onChange={props.handleChange('nom')}
                      />
                      <input
                        type="email"
                        placeholder="Adresse Mail"
                        value={props.values.email}
                        onChange={props.handleChange('email')}
                      />
                      {props.errors.email && props.touched.email ? <div className="errors">{props.errors.email}</div> : null}
                      <input
                        type="text"
                        placeholder="Téléphone"
                        value={props.values.phone}
                        onChange={props.handleChange('phone')}
                      />
                      {props.errors.phone && props.touched.phone ? <div className="errors">{props.errors.phone}</div> : null}

                    </div>
                    <ReCAPTCHA
                      sitekey={'6Lc2crUbAAAAAFdX2G8zDe_U3x7oOPUDH6l1-hP8'}
                      size="invisible"
                      ref={reRef}
                    />
                    <div className="contactButton" onClick={props.handleSubmit}>
                      <h5 className='inscriptionText'>ENVOYER</h5>
                    </div>
                  </form>
                )}

              </Formik>
            </div>
      </div>

    <Footer />
    </div>
  )
}
